name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_bd3b46999f3c4a117312da1ab60113eaf300f047
          SONAR_HOST_URL: https://sonar-hml.securityfirst.com.br
